name: 'Auto update flake'

on:
  workflow_dispatch:
  schedule:
    - cron: '37 17 * * *'

permissions:
  contents: write

jobs:
  auto-update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, master-git] # Defines the targets
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }} # Tells checkout which branch to use

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Update flake.lock
        run: nix flake update

      - name: Check flake health
        run: nix flake check

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ matrix.branch }} # Ensures it pushes back to the correct branch
          commit_message: 'build: auto-update flake.lock'
          file_pattern: 'flake.lock'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
